name: Build Linux
run-name: Build Linux
on:
  workflow_dispatch: {}
jobs:
  Build_Deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        dart pub global activate flutter_to_debian
    - run: python3 debian/build.py
    - uses: actions/upload-artifact@v3
      with:
        name: deb_build
        path: build/linux/x64/release/debian
 